### ISSUE TITLE
Hello, how can I connect Pi

### ISSUE THREAD

**Issue by jeff0213** [psykulsk/RpiANC#5]
Hello, how can I connect  pi

**Comment by jeff0213** [comment]
![1636708395(1)](https://user-images.githubusercontent.com/50932956/141442299-6282a489-bd88-4fe3-8a88-0a0a3f47303b.png)

**Comment by psykulsk** [comment]
Hi, you need to modify [these ](https://github.com/psykulsk/RpiANC/blob/master/Headers/constants.h#L11-L12) two values two the actual devices available on your Rpi. You can list all the devices using the `aplay` cmmand line utility ([aplay manpage](https://linux.die.net/man/1/aplay)), for example `aplay -l`.
