### ISSUE TITLE
Excuse me, how to adjust my parameters

### ISSUE THREAD

**Issue by logic88** [psykulsk/RpiANC#6]
pi@raspberrypi:~/RpiANC-master/build $ ./ffANC 
xcb_connection_has_error() returned true
Capture params: Capture rate: 44100 Period size: 32 Min period size: 32
Playback params: Playback rate: 44101 Period size: 444 Play min period size: 443 Buffer size: 32768
access type = RW_INTERLEAVED
subformat = 'STD' (Standard)
channels = 2
rate = 44101 bps
period time = 10068 us
period size = 444 frames
period size = 3552 bytes
buffer time = 10068 us
buffer size = 32768 frames
periods per buffer = 73 frames
 min period size = 444 frames
 min buffer size = 32768 frames
exact rate = 44101/1 bps
significant bits = 32
is batch = 1
is block transfer = 1
is double = 0
is half duplex = 0
is joint duplex = 0
can overrange = 0
can mmap = 0
can pause = 0
can resume = 0
can sync start = 0
Number of play frames per device buffer( 32768 ) then configuration ( 32856 )

**Comment by psykulsk** [comment]
Hello, 

You can change the parameters in the [constants.h](https://github.com/psykulsk/RpiANC/blob/master/Headers/constants.h) file, then recompile and try again.

Thanks!
